# Generated by Django 3.0.3 on 2020-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_Details',
            },
        ),
        migrations.CreateModel(
            name='College_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeName', models.CharField(max_length=50)),
                ('CollegeAddress', models.CharField(max_length=50)),
                ('Contact', models.CharField(default=None, max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'College_Details',
            },
        ),
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeId', models.CharField(max_length=50)),
                ('CourseName', models.CharField(max_length=50)),
                ('Subject1', models.CharField(default=None, max_length=50)),
                ('Subject2', models.CharField(default=None, max_length=50)),
                ('Subject3', models.CharField(default=None, max_length=50)),
                ('Subject4', models.CharField(default=None, max_length=50)),
                ('Subject5', models.CharField(default=None, max_length=50)),
                ('MinimumPerReq', models.CharField(default=None, max_length=50)),
                ('MinimumStudents', models.CharField(default=None, max_length=50)),
                ('StudentAccepted', models.IntegerField(blank=True, default=None, null=True)),
                ('SecondlastCutoff', models.CharField(default=None, max_length=100)),
                ('LastYearCutoff', models.CharField(default=None, max_length=100)),
                ('CurrentCutoff', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Course_Details',
            },
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Dob', models.CharField(default=None, max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(default=None, max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('CollegeOpt', models.CharField(default=None, max_length=100)),
                ('CourseOpt', models.CharField(default=None, max_length=100)),
                ('LastQualification', models.CharField(blank=True, max_length=100, null=True)),
                ('TenthPercentage', models.CharField(blank=True, max_length=100, null=True)),
                ('TwelfthPercentage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Student_Details',
            },
        ),
        migrations.CreateModel(
            name='Student_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeId', models.CharField(max_length=50)),
                ('CourseId', models.CharField(max_length=50)),
                ('Studentid', models.CharField(default=None, max_length=50)),
                ('Percentage', models.IntegerField(blank=True, null=True)),
                ('ListNumber', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'Student_List',
            },
        ),
    ]
