# Generated by Django 3.0.3 on 2020-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='MinimumStudents',
        ),
        migrations.AddField(
            model_name='course_details',
            name='MaximumStudents',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
