# Generated by Django 3.0.3 on 2020-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0002_auto_20200710_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='Subject6',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
