# Generated by Django 3.0.3 on 2020-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0003_course_details_subject6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='CurrentCutoff',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
