# Generated by Django 3.0.3 on 2020-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0004_auto_20200710_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_details',
            name='CollegeAddress',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college_details',
            name='CollegeName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='college_details',
            name='Website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='CollegeId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='CourseName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='Subject1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='Subject2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='Subject3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='Subject4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='Subject5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='Subject6',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student_list',
            name='CourseId',
            field=models.CharField(max_length=100),
        ),
    ]
