# Generated by Django 3.0.3 on 2020-07-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0005_auto_20200710_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeId', models.CharField(max_length=50)),
                ('CourseId', models.CharField(max_length=100)),
                ('Studentid', models.CharField(default=None, max_length=50)),
                ('Percentage', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'AppliedStudent',
            },
        ),
        migrations.CreateModel(
            name='SelectedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeId', models.CharField(max_length=50)),
                ('CourseId', models.CharField(max_length=100)),
                ('Studentid', models.CharField(default=None, max_length=50)),
                ('Percentage', models.IntegerField(blank=True, null=True)),
                ('ListNumber', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField()),
                ('Status', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'SelectedStudent',
            },
        ),
        migrations.DeleteModel(
            name='Student_List',
        ),
    ]
