# Generated by Django 3.0.3 on 2020-07-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0006_auto_20200710_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='MinimumQualification',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
