# Generated by Django 3.0.3 on 2020-07-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0007_course_details_minimumqualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='MinimumQualification',
            new_name='LastQualificationReq',
        ),
    ]
