# Generated by Django 3.0.3 on 2020-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0009_auto_20200711_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedstudent',
            name='StudentName',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
