# Generated by Django 3.0.3 on 2020-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0010_selectedstudent_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedstudent',
            name='Status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
