# Generated by Django 3.0.3 on 2020-07-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0011_appliedstudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedstudent',
            name='Percentage',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
