# Generated by Django 3.0.3 on 2020-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollegeAdmission', '0013_auto_20200713_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='StudentAccepted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
